name: image
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Downloading tools
        run: |
          pip install ffmpeg ffpb rclone

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Download video
        run: |
          mkdir work
          cd work && curl "https://share.secretz.workers.dev/2:/Folder.zip" -o Folder.zip && unzip Folder.zip

      - name: Encode video
        run: |
          cd work && pwd && mkdir encode
          for input_video in $(find . -name "*.jpg"); do
            output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .jpg)_encoded.webp"
            ffpb -i "$input_video" "$output_video"
          done
          
      - name: zip
        run: |
         cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Upload
          path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
          
