name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg
       wget https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x265 -O x265
       sudo mv -v x265 /usr/local/bin
       chmod a+rx /usr/local/bin/x265
       x265 --version
       
    - name: Pull Docker Image
      run: |
       docker pull helpless69/av1an:test
        
    - name: Download video
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && pwd && curl "https://share.secretz.workers.dev/2:/output.mkv" -o vid.mkv && ffmpeg -i vid.mkv -codec copy -t 15 video.mkv

    - name: Encode
      run: |
        cd /home/runner/encode && pwd && ls
        wget https://raw.githubusercontent.com/helpless69/bookish-computing-machine/main/Dockerfile -O Dockerfile
        sudo docker build -t encode:test .
        docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -t encode:test -i "video.mkv" -w 0 -e x265 -c mkvmerge -o "Output.mkv"
        
    - name: Zip
      run: |
        rm /home/runner/encode/vid.mkv && cd /home/runner && zip -r encode.zip encode

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode.zip
