name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install rclone
    - name: Pull Docker Image
      run: |
        docker pull helpless69/av1an:latest
        
    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/Upscale/video.mp4" -o video.mp4
    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: Encode
      run: |
        cd $HOME && cd encode
        docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -t --rm helpless69/av1an:latest -i "video.mkv" --probing-rate 2 --target-quality 94 --vmaf --resume -e x265 -c mkvmerge --verbose " -c:a copy " -v " -p slow --crf 21.5 " -w 4 -o "Output.mkv"
        
    - name: Zip
      run: |
        cd $HOME

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode/Output.mkv
