name: Av1an

on: workflow_dispatch
  
jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: build
      run: |
        wget https://share.secretz.workers.dev/2:/S01E01.mkv
        git clone https://github.com/master-of-zen/Av1an
        cd Av1an && docker build -t "av1an" .
