name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install ffpb rclone
    - name: Pull Docker Image
      run: |
        docker pull masterofzen/av1an:master
        
    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/Bocchi%20the%20Rock!%20(BD%201080p%20HEVC%20Opus)%20%5BRecluse%5D/Extras/%5BRecluse%5D%20Bocchi%20the%20Rock!%20-%20NCED%2001%20(BD%201080p%20HEVC%20Opus)%20%5B361CD212%5D.mkv" -o Video.mkv
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: Encode
      run: |
        cd $HOME && cd encode
        docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -t --rm masterofzen/av1an:master -i "Video.mkv" --resume -x 240 -e svt-av1 -c mkvmerge -m dgdecnv --verbose --set-thread-affinity=2 -a " -c:a copy " -v " --lp 2 --keyint 0 --enable-qm 1 --qm-min 0 --qm-max 15 --enable-overlays 1 --aq-mode 2 --color-primaries 1 --transfer-characteristics 1 --matrix-coefficients 1 --color-range 0 --film-grain-denoise 0 --tune 0 --preset 4 --crf 28 " --photon-noise=6 --chroma-noise -w 4 -o "Output.mkv"
        
    - name: Zip
      run: |
        cd $HOME

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode/Output.mkv
