name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install ffpb rclone
    - name: Pull Docker Image
      run: |
        docker pull masterofzen/av1an:master
        
    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/The.Railway.Men.The.Untold.Story.of.Bhopal.1984.S01E01.1080p.NF.WEB-DL.HIN-ENG-TAM-TEL.DDP5.1.x264-Telly.mkv" -o Video.mkv
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: Encode
      run: |
        cd $HOME && cd encode
        for input_video in $(find . -name "*.mkv"); do
          output_video="$HOME/encode/$(basename $input_video .mkv).mkv"
          docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -t --rm masterofzen/av1an:master -w 2 -i "Video.mkv" --ffmpeg " -map 0 -c:s copy" --concat mkvmerge --verbose -e x265 -v " -p slow --rc-lookahead 50 --rdoq-level 2 --bframes 8 --ref 4 --subme 3 --qcomp 0.60 --aq-mode 3 --aq-strength 1.00 --psy-rd 2.00 --psy-rdoq 1.00 --no-sao --crf 24 " -a="-c:a libopus -ac 2 -b:a 128k" -o "Output.mkv"
        done

    - name: Zip
      run: |
        cd $HOME

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode/Output.mkv
