name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg

    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/rest.mkv" -o Video.mkv

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev
        
    - name: Pull Av1an Docker Image
      run: docker pull masterofzen/av1an

    - name: Encode
      run: |
        cd /home/runner/encode
        for input_video in $(find . -name "*.mkv"); do
          output_video="/home/runner/encode/$(basename $input_video .mkv).mkv"
          docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -i --rm masterofzen/av1an:latest -i "Video.mkv" --ffmpeg " -map 0 -c:s copy " --concat mkvmerge --verbose --resume -e x265 -v " -p slow --rc-lookahead 120 --crf 23 " -a="-c:a libopus -ac 2 -b:a 128k" -o "Output.mkv"
        done

    - name: zip
      run: |
        cd /home/runner/encode

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/encode/Output.mkv
