name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install rclone
    - name: Pull Docker Image
      run: |
        docker pull helpless69/av1an:latest
        
    - name: Download video
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && pwd && curl "https://share.secretz.workers.dev/2:/Upscale/video.mp4" -o video.mp4

    - name: Encode
      run: |
        cd /home/runner/encode && pwd
        docker run --privileged -v "/home/runner/encode" --user $(id -u):$(id -g) -t --rm helpless69/av1an:latest -i "video.mkv" --probing-rate 2 --target-quality 95 --vmaf --resume -e x265 -c mkvmerge --verbose -v " -p slow --crf 23 " -w 4 -o "Output.mkv"
        
    - name: Zip
      run: |
        cd $HOME

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode/Output.mkv
