name: Av1an

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Cache tools
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          /usr/local/bin
        key: ${{ runner.os }}-tools-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-tools-

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/apt.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Download video
      run: |
       cd $HOME && pwd
       cd work && pwd && curl "https://share.secretz.workers.dev/2:/S01E01.mkv" -o input.mkv

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: Cache Av1an source
      uses: actions/cache@v2
      with:
        path: |
          ~/Av1an
        key: ${{ runner.os }}-av1an-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-av1an-

    - name: Build and Install av1an
      run: |
        cd /home/runner/ && git clone https://github.com/master-of-zen/Av1an
        cd Av1an && docker build -t "av1an" .

    - name: Encode
      run: |
        cd /home/runner/work && mkdir encode && chmod a+rx /usr/local/bin/av1an && chmod a+rx /usr/local/bin/rav1e
        for input_video in $(find . -name "*.mkv"); do
          output_video="/home/runner/work/encode/$(basename $input_video .mkv).mkv"
          av1an -i "$input_video" "$output_video"
        done

    - name: zip
      run: |
       cd /home/runner/work/ && zip -r encode.zip encode

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/work/encode.zip
