name: nerdy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading tools
        run: |
          pip install yt-dlp wget ffmpeg rclone

      - name: Download video
        run: |
          mkdir work
          cd work
          yt-dlp -o input -f best https://youtu.be/tbnLqRW9Ef0

      - name: step 2
        run: |
          cd work
          ls
 
