name: nerdy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Downloading tools
        run: |
          pip install yt-dlp wget ffmpeg rclone

      - name: Download video
        run: |
          mkdir work
          cd work
          yt-dlp -o input.mp4 -S "res:720" https://www.pornhub.com/view_video.php?viewkey=ph62954130e663d

      - name: Encode video to HEVC
        run: |
          cd work && pwd
          ffmpeg -i input.mp4 -map 0 -tune grain -c:v libx265 -pix_fmt yuv420p10le -crf 24 -c:a aac -b:a 128k output.mkv   
 
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      
      - run: wget https://raw.githubusercontent.com/Helpless69/bookish-computing-machine/main/rclone -O run && bash run
