name: nerdy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading tools
        run: |
          pip install yt-dlp wget ffmpeg rclone

      - name: Download video
        run: |
          mkdir work
          cd work
          yt-dlp -o input.mp4 -f best https://youtu.be/tbnLqRW9Ef0

      - name: Encode video to HEVC
        run: |
          cd work
          ffmpeg -i input.mp4 -map 0 -c:v libx265 -preset slow -pix_fmt yuv420p10le -crf 20 -c:a copy output.mkv
              
      - name: Configure rclone
        run: |
          rclone config file
