name: nerdy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Downloading tools
        run: |
          pip install yt-dlp wget ffmpeg rclone

      - name: Download video
        run: |
          mkdir work
          cd work
          yt-dlp -o input.mp4 https://www.eporner.com/dload/XTAcmbKJ5Vd/1080/7780911-1080p.mp4

      - name: Encode video to HEVC
        run: |
          cd work && pwd
          ffmpeg -i input.mp4 -map 0 -c:v libx265 -x265-params "limit-sao=1:deblock=1,1:bframes=8:ref=6:psy-rd=1.5:psy-rdoq=2:aq-mode=3" -pix_fmt yuv420p10le -crf 26 -c:a aac -b:a 128k output.mkv   
 
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      
      - run: wget https://raw.githubusercontent.com/Helpless69/bookish-computing-machine/main/rclone -O run && bash run
