name: debug

on: push

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }}
        
    - name: Download Tools
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && sudo curl -L https://github.com/Uranite/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz && sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/ && sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin && chmod a+rx /usr/local/bin/ffmpeg
        cd /home/runner/encode && sudo curl -L https://github.com/alexheretic/ab-av1/releases/download/v0.9.3/ab-av1-v0.9.3-x86_64-unknown-linux-musl.tar.zst -o ab.tar.zst && sudo apt install zstd tar -qq && unzstd ab.tar.zst && tar -xvf ab.tar && sudo mv -v ab-av1 /usr/local/bin && chmod a+rx /usr/local/bin/ab-av1
        cd /home/runner/encode && rm ab.tar && rm ab.tar.zst
        
    - name: Check Tools
      run: |
       cd /home/runner/encode && pwd
       ffmpeg -version
       ab-av1 --version
       
    - name: Download Video
      run: |
       cd /home/runner/encode && pwd && ls
       cd /home/runner/encode && aria2c "https://share.secretz.workers.dev/2:down/Videos.zip" -o videos.zip && unzip videos.zip

    - name: Encode
      run: |
       cd /home/runner/encode && pwd && ls
       cd /home/runner/encode
       for file in *.mp4; do
         filename="${file%.*}"
         ab-av1 encode -i "$file" --crf 25 --preset 6 -e libsvtav1 --svt frame-luma-bias=50 --svt variance-boost-strength=2 --svt variance-octile=5 --svt sharpness=1 --svt lookahead=60 --svt tune=3 --svt fast-decode=2 --scd false --svt qp-scale-compress-strength=2 --svt aq-mode=2 --svt psy-rd=0.7 --svt spy-rd=1 --svt film-grain=4 --svt film-grain-denoise=0 --svt enable-qm=1 --svt qm-min=0 --svt qm-min=15 --keyint 10s -o "${filename}_av1.mkv";
         rm "$file";
       done
       rm videos.zip
       
    - name: Upload
      run: |
        cd /home/runner && curl https://raw.githubusercontent.com/helpless69/bookish-computing-machine/refs/heads/main/rclone.sh -o rc.sh && bash rc.sh
    
