name: debug

on: push

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

       
    - name: Pull Docker Image
      run: |
       docker pull fr3akyphantom/vapoursynth-av1an-runtime:latest
        
    - name: Download video
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && pwd && curl "https://worker-rough-violet-c3b3.retix39856.workers.dev/8b41336ab9357e4a49b8b5a536e83e7bfc5f4ac8b0dd3e3491a69473798de68fe4630c38aad401ec7bbc16befb01253748892f1592f4e7ed88fbc3550992d663b21b19f96f039df4da52756cf3684476f7651090ee6c8d8dafee741a6bc62380248b8a9c4687d283aa304831b7c55aefeec256bc8eeba35acffd3b79a6463367de654a522615079cbd6b6823adff0f8b7e0fb4858467ee5fcf2bbe3fbd0aa2f4f5971c69f91e8fc76523f2dbfe998c55::27855df6fb74ca53c0b09c1129b4d39c/Suits%20S01E01%201080p%20Bluray%20[Hindi%20DDP2.0%20%20English%20DD5.1]%20x264%20(EbPIonicboy).mkv" -o video.mkv && curl "https://raw.githubusercontent.com/helpless69/bookish-computing-machine/refs/heads/main/bash.sh" -o bash.sh
        
    - name: Versions Check
      run: |
       docker run --privileged --user root --entrypoint /bin/bash -v "/home/runner/encode":/videos -t fr3akyphantom/vapoursynth-av1an-runtime:latest -c "
       ffmpeg -hide_banner -version && \
       x265 -V && \
       rav1e --version && \
       SvtAv1EncApp --version && \
       vspipe --version && \
       av1an --version"
       
    - name: Encode
      run: |
       cd /home/runner/encode && pwd && ls
       docker run --privileged --user root --entrypoint /bin/bash -v "/home/runner/encode":/videos -t fr3akyphantom/vapoursynth-av1an-runtime:latest -c "bash bash.sh"
       
    - name: Zip
      run: |
        rm /home/runner/encode/video.mkv && cd /home/runner && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Upload
        path: /home/runner/encode.zip
