name: debug

on: push

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }}
        
    - name: Download Tools
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && pwd && sudo curl -L https://github.com/Uranite/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz && sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/ && sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin && chmod a+rx /usr/local/bin/ffmpeg
        cd /home/runner/encode && pwd && sudo curl -L https://github.com/alexheretic/ab-av1/releases/download/v0.9.3/ab-av1-v0.9.3-x86_64-unknown-linux-musl.tar.zst -o ab.tar.zst && sudo apt install zstd tar -qq && unzstd /content/ab.tar.zst && tar -xvf /content/ab.tar && sudo mv -v /content/ab-av1 /usr/local/bin && chmod a+rx /usr/local/bin/ab-av1

    - name: Check Tools
      run: |
       cd /home/runner/encode && pwd
       ffmpeg -version
       ab-av1 --version
       
       
    - name: Encode
      run: |
       cd /home/runner/encode && pwd && ls
    
      
    - name: Upload
      run: |
        cd /home/runner && curl https://raw.githubusercontent.com/helpless69/bookish-computing-machine/refs/heads/main/rclone.sh -o rc.sh && bash rc.sh
    
