name: debug
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: setup ffmpeg
      run: |
          pip install ffpb
          sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
          sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
          sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
          chmod a+rx /usr/local/bin/ffmpeg

    - name: setup x265
      run: |
          wget https://share.secretz.workers.dev/2:down/x265
          sudo mv -v x265 /usr/local/bin && chmod a+rx /usr/local/bin/x265

    - name: Downloading tools
      run: |
       pip install ffpb
    
    - name: Install Dependencies
      run: |
        sudo apt-get install cmake cmake-curses-gui build-essential yasm
    
    - name: Start SSH via ngrok
      uses: rdp-studio/ssh2actions@main
      with:
          mode: ngrok
      env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
