name: debug

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

       
    - name: Pull Docker Image
      run: |
       docker pull fr3akyphantom/vapoursynth-av1an-runtime:latest
        
    - name: Download video
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && pwd && curl "https://share.secretz.workers.dev/2:/ep13.mkv" -o video.mkv
    - name: Versions Check
      run: |
       docker run --privileged --user root --entrypoint /bin/bash -v "/home/runner/encode":/videos -t fr3akyphantom/vapoursynth-av1an-runtime:latest -c "
       ffmpeg -hide_banner -version && \
       x265 -V && \
       rav1e --version && \
       SvtAv1EncApp --version && \
       vspipe --version && \
       av1an --version"
       
    - name: Encode
      run: |
       cd /home/runner/encode && pwd && ls
       docker run --privileged --user root --entrypoint /bin/bash -v "/home/runner/encode":/videos -t fr3akyphantom/vapoursynth-av1an-runtime:latest -c "
       av1an -i video.mkv -e svt-av1 --photon-noise 4 --vmaf -w 2 --set-thread-affinity 2 -m lsmash -v ' --rc 0 --crf 28 --preset 6 --aq-mode 2 --variance-boost-strength 4 --variance-octile 4 --sharpness 2 --enable-restoration 0 --enable-dlf 2 --enable-tf 0 --keyint -1 --lookahead 120 --tune 3 --enable-qm 1 --qm-min 0 --qm-max 15 --adaptive-film-grain 1 --film-grain-denoise 0 --film-grain 6 --enable-overlays 0 --enable-cdef 0 --color-primaries 1 --transfer-characteristics 1 --matrix-coefficients 1 ' -c mkvmerge -o Output.mkv"
       
    - name: Zip
      run: |
        rm /home/runner/encode/video.mkv && cd /home/runner && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode.zip
