name: encode
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading tools
        run: |
          pip install ffpb rclone
          sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
          sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
          ls /usr/local/bin/
          
          
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }} 

      - name: Download video
        run: |
          mkdir work
          cd work && curl "https://share.secretz.workers.dev/2:/VID_20190131_132237353_HDR.mp4" -o Video.mp4

      - name: Encode video
        run: |
          cd work && pwd && mkdir encode
          for input_video in $(find . -name "*.mp4"); do
            output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mp4).mp4"
            ffmpeg -i "$input_video" -vf scale=1920:1080 -c:v libsvtav1 -pix_fmt yuv420p10le -preset 6 -crf 24 -g 300 -svtav1-params tune=0,film-grain=10 "$output_video"
          done
          
      - name: zip
        run: |
         cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Upload
          path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
