name: encode1
on: workflow_dispatch

jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders
      
      
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }} 

    - name: Download video
      run: |
       mkdir work
       cd work && curl "https://share.secretz.workers.dev/2:/split-003.mp4" -o Video.mp4
    - name: Encode video
      run: |
       cd work && pwd && mkdir encode
       for input_video in $(find . -name "*.mp4"); do
         output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mp4).mp4"
         ffpb -i "$input_video" -map 0 -c:v libsvtav1 -svtav1-params enable-qm=1:qm-min=0:qm-max=15:aq-mode=0:irefresh-type=1:keyint=10s:tune=0:lookahead=120:enable-tf=1:color-primaries=1:transfer-characteristics=1:matrix-coefficients=1:color-range=0:enable-overlays=1:chroma-u-dc-qindex-offset=-1:chroma-u-ac-qindex-offset=-1:chroma-v-dc-qindex-offset=-1:chroma-v-ac-qindex-offset=-1  -crf 24 -preset 6 -pix_fmt yuv420p10le "$output_video"
        done
      
    - name: zip
      run: |
       cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
