name: encode

on: push

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg
       wget https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x265 -O x265
       sudo mv -v x265 /usr/local/bin
       chmod a+rx /usr/local/bin/x265
       x265 --version
       
    - name: Pull Docker Image
      run: |
       docker pull helpless69/av1an:test
        
    - name: Download video
      run: |
        cd /home/runner && pwd && mkdir encode
        cd /home/runner/encode && pwd && curl "https://share.secretz.workers.dev/2:/Upscale/video.mp4" -o video.mp4

    - name: Encode
      run: |
       cd /home/runner/encode && pwd && ls
       wget https://raw.githubusercontent.com/helpless69/bookish-computing-machine/main/Dockerfile -O Dockerfile
       sudo docker build -t encode:test .
       docker run --privileged --user root --entrypoint /bin/bash -v "/home/runner/encode":/videos -t encode:test -c "
       av1an -i video.mp4 -e svt-av1 --resume --verbose --target-quality 95 --vmaf --crf 24.0-55.0 --preset 6 --aq-mode 2 --variance-boost-strength 4 --variance-octile 4 --sharpness 2 --frame-luma-bias 100 --enable-dlf 2 --enable-tf 0 --keyint 0 -c mkvmerge -o Output.mkv"
     
    - name: Zip
      run: |
        rm /home/runner/encode/video.mp4 && cd /home/runner && zip -r encode.zip encode

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode.zip
