name: Av1an test

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set PATH
      run: |
        export PATH="/usr/local/bin:${PATH}"
      shell: bash

    - name: Downloading tools
      run: |
       pip install rclone
       wget https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x265 -O x265
       sudo mv -v x265 /usr/local/bin
       chmod a+rx /usr/local/bin/x265
       wget https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x264 -O x264
       sudo mv -v x264 /usr/local/bin
       chmod a+rx /usr/local/bin/x264
       x264 --version
       x265 --version
       
    - name: Pull Docker Image
      run: |
        docker pull helpless69/av1an:test
        
    - name: Download video
      run: |
        mkdir -p /home/runner/encode && cd /home/runner/encode
        curl -L "https://share.secretz.workers.dev/2:/output.mkv" -o video.mkv

    - name: Encode
      run: |
       docker run --privileged --user root --entrypoint /bin/bash -v "/home/runner/encode":/videos helpless69/av1an:test -c "
       rm -f /usr/bin/x264 && curl -L https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x264 -o x264 && chmod 777 x264 && \
       mv -v x264 /usr/bin/x264 && \
       x264 --version && \
       rm -f /usr/bin/x265 && curl -L https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x265 -o x265 && chmod 777 x265 && \
       mv -v x265 /usr/bin/x265 && \
       x265 --version && \
       whereis SvtAv1EncApp && \
       av1an -i video.mkv --verbose -w 2 --target-quality 95 --vmaf --resume -e svt-av1 -c mkvmerge -o Output.mkv"
     
    - name: Zip
      run: |
        rm /home/runner/encode/video.mkv && cd /home/runner && zip -r encode.zip encode

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode.zip
