name: encode

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Pull Docker Image
      run: |
        docker pull masterofzen/av1an:master
        
    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/split-003.mp4" -o Video.mp4
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: Encode
      run: |
        cd $HOME && cd encode
        docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -t --rm masterofzen/av1an:master --set-thread-affinity 4 -i "Video.mp4" --ffmpeg " -map 0 -c:s copy" --concat mkvmerge --force --verbose -e svt-av1 --video-params "--crf 28 --aq-mode 0 --tune 0 --keyint 0 --lookahead 120 --irefresh-type 1 --lp 2 --color-primaries 1 --transfer-characteristics 1 --matrix-coefficients 1 --color-range 0 --enable-overlays 1 --scd 0 --enable-tf 0 --chroma-u-dc-qindex-offset -1 --chroma-u-ac-qindex-offset -1 --chroma-v-dc-qindex-offset -1 --chroma-v-ac-qindex-offset -1 --enable-qm 1 --qm-min 0 --qm-max 15 --preset 4" --pix-format yuv420p10le -a="-c:a aac -ac 2 -b:a 128k" -o "Output.mp4"
    - name: Zip
      run: |
        cd $HOME

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode/Output.mp4
        
