name: encode
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Downloading tools
        run: |
          pip install ffmpeg ffpb rclone

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Download video
        run: |
          mkdir work
          cd work && curl "https://share.secretz.workers.dev/2:/VID_20190131_132237353_HDR.mp4" -o Video.mp4

      - name: Encode video
        run: |
          cd work && pwd && mkdir encode
          for input_video in $(find . -name "*.mp4"); do
            output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mp4).mp4"
            ffpb -i "$input_video" -vf scale=1920:1080 -c:v libsvtav1 -pix_fmt yuv420p10le -preset=6 -crf 24 -g 300 -svtav1-params tune=0:film-grain-denoise=1:film-grain=4 "$output_video"
          done
          
      - name: zip
        run: |
         cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Upload
          path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
