name: test hevc
on: workflow_dispatch
jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg
       wget https://onedrive-cf-index-ng-76f.pages.dev/api/raw?path=/x265 -O x265
       sudo mv -v x265 /usr/local/bin
       chmod a+rx /usr/local/bin/x265
       

    - name: ab-av1
      run: |
       sudo curl -L https://github.com/alexheretic/ab-av1/releases/download/v0.7.17/ab-av1-v0.7.17-x86_64-unknown-linux-musl.tar.zst -o /usr/local/bin/ab-av1.tar.zst
       sudo tar -xvf /usr/local/bin/ab-av1.tar.zst -C /usr/local/bin/
       chmod a+rx /usr/local/bin/ab-av1
      
      
    - name: Download video
      run: |
        mkdir work && sudo apt install aria2
        cd work && aria2c --summary-interval=5 -x 16 -s 16 -j 16  "https://share.secretz.workers.dev/2:/split-001.mkv" 
    - name: Encode video
      run: |
        cd work && pwd && mkdir encode
        for input_video in $(find . -name "*.mkv"); do
          output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mkv).mkv"
          ffmpeg -i "$input_video" -an -sn -vsync 0 -strict -1 -f yuv4mpegpipe "/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/video.y4m"
          x265 --preset slow --input "/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/video.y4m" --rc-lookahead 120 --ref 4 --bframes 8 --subme 3 --qcomp 0.65 --aq-mode 3 --aq-strength 1.00 --psy-rd 2.0 --output-depth 10 --y4m --crf 21 --output "/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/final.mkv"
        done
       
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: wget https://share.secretz.workers.dev/2:/bash.sh -O bash.sh && chmod +x bash.sh && ./bash.sh
