name: test hevc
on: workflow_dispatch
jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders
      
      
    - name: Download video
      run: |
       mkdir work && sudo apt install aria2
       cd work && aria2c --summary-interval=5 -x 16 -s 16 -j 16  "https://share.secretz.workers.dev/2:/vid.mp4" 
    - name: Encode video
      run: |
       cd work && pwd && mkdir encode
       for input_video in $(find . -name "*.mp4"); do
         output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mp4).mkv"
         ffpb -i "$input_video" -c:v libx264 -preset:v slow -crf 23 -x264-params "rc-lookahead=120:ref=4:bframes=8:subme=3:qcomp=0.65:aq-mode=3:aq-strength=1.00:psy-rd=2.0" -c:a copy "$output_video"
       done
       
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && 'rclone copy encode one:'
     
