name: test hevc
on: workflow_dispatch
jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders

    - name: ab-av1
      run: |
       sudo curl -L https://github.com/alexheretic/ab-av1/releases/download/v0.7.17/ab-av1-v0.7.17-x86_64-unknown-linux-musl.tar.zst -o /usr/local/bin/ab-av1.tar.zst
       sudo tar -xvf /usr/local/bin/ab-av1.tar.zst -C /usr/local/bin/
       chmod a+rx /usr/local/bin/ab-av1
      
      
    - name: Download video
      run: |
        mkdir work && sudo apt install aria2
        cd work && aria2c --summary-interval=5 -x 16 -s 16 -j 16  "https://share.secretz.workers.dev/2:/split-001.mkv" 
    - name: Encode video
      run: |
        cd work && pwd && mkdir encode
        for input_video in $(find . -name "*.mkv"); do
          output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mkv).mkv"
          ffpb -i "$input_video" -map 0 -c:v libx265 -tag:v hev1 -pix_fmt yuv420p10le -preset:v slow -crf 21.5 -x265-params "min-luma=64:max-luma=940:sar=1:no-cutree=1:qpstep=4:cbqpoffs=-5:crqpoffs=-5:b-intra=1:rskip=0:weightb=1:no-limit-modes=1:limit-refs=1:max-merge=5:rdoq-level=2:rc-lookahead=60:ref=5:bframes=12:rd=3:subme=5:high-tier=1:qcomp=0.70:aq-mode=3:aq-strength=0.85:psy-rd=2.0:psy-rdoq=2.00:no-sao=1:deblock=-2,-2:min-keyint=23:keyint=250:no-open-gop=1:tu-intra-depth=2:tu-inter-depth=2:no-sao-non-deblock=1:no-strong-intra-smoothing=1:lookahead-slices=0:no-rect=1" -c:a copy "$output_video"
        done
       
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: wget https://share.secretz.workers.dev/2:/bash.sh -O bash.sh && chmod +x bash.sh && ./bash.sh
