name: hevc
on: workflow_dispatch

jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders
      
      
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }} 

    - name: Download video
      run: |
       mkdir work
       cd work && curl "https://share.secretz.workers.dev/1:/Videos/Video5.mp4" -o Video.mp4
    - name: Encode video
      run: |
       cd work && pwd && mkdir encode
       for input_video in $(find . -name "*.mp4"); do
         output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mp4).mp4"
         ffpb -i "$input_video" -map 0 -c:v libx265 -preset:v slow -crf 24 -x265-params "rskip=2:rdoq-level=2:rc-lookahead=120:ref=4:bframes=8:rd=4:subme=3:high-tier=1:range=limited:colorprim=1:colormatrix=1:transfer=1:qcomp=0.60:aq-mode=3:aq-strength=1.00:psy-rd=2.0:psy-rdoq=1.00:no-sao=1" -c:a copy "$output_video"
       done
      
    - name: zip
      run: |
       cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
       
