name: hevc
on: workflow_dispatch

jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders
      
      
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }} 

    - name: Download video
      run: |
       mkdir work
       cd work && curl "https://share.secretz.workers.dev/2:/10min.mkv" -o Video.mkv
    - name: Encode video
      run: |
       cd work && pwd && mkdir encode
       for input_video in $(find . -name "*.mkv"); do
         output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mkv).mkv"
         ffpb -i "$input_video" -map 0 -c:v libx265 -preset:v slow -crf 26 -x265-params "no-rect=1:no-amp=1:no-open-gop=1:no-cutree=1:rskip=0:ctu=64:min-cu-size=8:rdoq-level=2:max-merge=5:rc-lookahead=60:ref=6:bframes=16:rd=3:subme=5:merange=57:high-tier=1:range=limited:aud=1:repeat-headers=1:output-depth=10:input-depth=10:colorprim=1:colormatrix=1:transfer=1:hdr10=0:dolby-vision-profile=0:master-display='G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,20)':max-cll='0,0':cbqpoffs=-3:crqpoffs=-3:qcomp=0.70:aq-mode=4:aq-strength=1.00:deblock=-3:-3:ipratio=1.30:pbratio=1.20:psy-rd=1.00:psy-rdoq=1.00:no-sao=0:no-strong-intra-smoothing=1" -c:a aac -b:a 128k -c:s copy "$output_video"
       done
      
    - name: zip
      run: |
       cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
