name: Docker Image

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        git clone https://github.com/Helpless69/Av1an
        cd Av1an
        docker build -t "helpless69/av1an" .

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u helpless69 --password-stdin

    - name: Tag and Push Docker Image
      run: |
        docker tag helpless69/av1an:test
        docker push helpless69/av1an:test
