name: test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - uses: actions/checkout@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Downloading tools
        run: |
          pip install ffmpeg ffpb rclone yt-dlp

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Setup Upscaler
        run: |
          mkdir work && pwd
          cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && git clone https://github.com/xinntao/Real-ESRGAN.git
          cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/Real-ESRGAN
          pip install basicsr
          pip install facexlib
          pip install gfpgan
          pip install -r requirements.txt
          python setup.py develop

      - name: Download video
        run: |
          cd work && cd Real-ESRGAN && yt-dlp -o video.mp4 https://www.tiktok.com/@fiona.szee/video/7049012484023291162


      - name: Upscale
        run: |
          cd work && cd Real-ESRGAN
          python inference_realesrgan_video.py -n RealESRGAN_x4plus -i video.mp4 -s 8 --face_enhance
          
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Upload
          path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/Real-ESRGAN/results/*
