name: x265
on:
  push:
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/helpless69/ffmpeg/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders
      
      
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }} 

    - name: Download video
      run: |
       mkdir work && sudo apt install aria2
       cd work && aria2c --summary-interval=5 -x 16 -s 16 -j 16  "https://share.secretz.workers.dev/1:/Fansly%202023-09-05%EF%BC%8CA%20maid%20cafe%20with%20hidden%20services,%20a%20set%20up%20by%20bad%20girl,%20and%20then%20squeezed%20to%20dry%2028min.mp4" -o Video.mp4
    - name: Encode video
      run: |
       cd work && pwd && mkdir encode
       for input_video in $(find . -name "*.mp4"); do
         output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .mp4).mp4"
         ffpb -y -i "$input_video" -threads 4 -vf "scale=1920:1080:force_original_aspect_ratio=decrease" -pix_fmt yuv420p10le -map 0 -c:s copy -c:v libx265 -preset:v slow -crf 23 -x265-params "aq-bias-strength=1.00:rskip=0:rdoq-level=2:rc-lookahead=120:ref=5:bframes=8:rd=4:subme=5:high-tier=1:range=limited:colorprim=1:colormatrix=1:transfer=1:qcomp=0.70:aq-mode=3:aq-strength=0.80:psy-rd=2.0:psy-rdoq=2.00:no-sao=1:output-depth=10:deblock=-2,-2:min-keyint=23:keyin=240:no-open-gop=true:tu-intra-depth=2:tu-inter-depth=2:no-sao-non-deblock=true:no-strong-intra-smoothing=true:b-intra=true:weightb=true:cbqpoffs=-2:crqpoffs=-2:no-cutree=true:qpstep=2:no-rect=true:tskip=true" -c:a aac -b:a 128k -ac 2 "$output_video"
       done
      
    - name: zip
      run: |
       cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
