name: x265
on:
  push:
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest 
    timeout-minutes: 9999
  
    steps:
    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/helpless69/ffmpeg/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg 
       ffmpeg -encoders
      
      
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }} 

    - name: Download video
      run: |
       mkdir work && sudo apt install aria2
       cd work && aria2c --summary-interval=5 -x 16 -s 16 -j 16  "https://helpless69.vercel.app/api/raw/?path=/Lolipop/Video/Quickie%20during%20my%20friend's%20wedding.m4v" -o Video.m4a
    - name: Encode video
      run: |
       cd work && pwd && mkdir encode
       for input_video in $(find . -name "*.m4a"); do
         output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename $input_video .m4a).mkv"
         ffpb -y -i "$input_video" -threads 0 -pix_fmt yuv420p10le -map 0 -c:s copy -c:v libx265 -preset:v slow -crf 24 -x265-params "aq-bias-strength=1.00:rskip=2:rdoq-level=2:rc-lookahead=120:ref=4:bframes=8:rd=4:subme=3:high-tier=1:range=limited:colorprim=1:colormatrix=1:transfer=1:qcomp=0.70:aq-mode=3:aq-strength=0.80:psy-rd=2.0:psy-rdoq=2.00:no-sao=1:output-depth=10:deblock=-2,-2:min-keyint=23:keyin=240:no-open-gop=1:tu-intra-depth=2:tu-inter-depth=2:no-sao-non-deblock=1:no-strong-intra-smoothing=1:qpstep=2" -c:a aac -b:a 128k -ac 2 "$output_video"
       done
      
    - name: zip
      run: |
       cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
       name: Upload
       path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
