name: actions control
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
       rclone_config: ${{ secrets.RCLONE_CONFIG }}

    - name: setup ffmpeg
      run: |
          pip install ffpb
          sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
          sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
          sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
          chmod a+rx /usr/local/bin/ffmpeg
          
    - uses: actions/checkout@v4
    - name: setup ab-av1
      run: cargo install --git https://github.com/alexheretic/ab-av1
        
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
