name: mega
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
      - name: Downloading tools
        run: |
          pip install ffpb rclone
          sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
          sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
          sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
          chmod a+rx /usr/local/bin/ffmpeg 
          ffmpeg -encoders
          
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }} 

      - name: Download video
        run: |
          mkdir work
          cd work && curl "https://share.secretz.workers.dev/2:/LovingEli1_212.mp4" -o Video.mp4

      - name: Encode videos
        run: |
          mkdir -p /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode
          find . -type f -name "*.mp4" | while read -r input_video; do
            output_video="/home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode/$(basename "$input_video" .mp4).mp4"
            ffpb -i "$input_video" -preset slow -c:v libx265 -x265-params "frame-threads=5:numa-pools=+:pmode=1:ref=6:min-keyint=24:gop-lookahead=0:bframes=16:b-adapt=2:b-pyramid=1:rc-lookahead=60:tu-inter-depth=4:tu-intra-depth=4:max-merge=3:limit-modes=1:me=3:subme=4:merange=57:weightp=1:weightb=1:deblock=-1,-1:b-intra=1:psy-rd=1.0:psy-rdoq=1.2:cbqpoffs=-1:crqoffs=-1:crf=26:qcomp=0.65:aq-mode=3:aq-strength=0.90:hist-threshold=0.03:no-limit-sao=1:qp-adaptation=1" -pix_fmt yuv420p10le -c:a aac -b:a 128k "$output_video"
          done
          
      - name: zip
        run: |
         cd /home/runner/work/bookish-computing-machine/bookish-computing-machine/work && zip -r encode.zip encode

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Upload
          path: /home/runner/work/bookish-computing-machine/bookish-computing-machine/work/encode.zip
