name: ATest

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg

    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/60s.mkv" -o Video.mkv

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev
        
    - name: Pull Av1an Docker Image
      run: docker pull masterofzen/av1an

    - name: Start SSH via ngrok
      uses: rdp-studio/ssh2actions@main
      with:
        mode: ngrok
      env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: us
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          

    - name: Encode
      run: |
        cd $HOME/work && mkdir encode
        for input_video in $(find . -name "*.mkv"); do
          output_video="$HOME/work/encode/$(basename $input_video .mkv).mkv"
          /path/to/Av1an/target/release/av1an -i "$input_video" "$output_video"
        done

    - name: Zip
      run: |
        cd $HOME/work && zip -r encode.zip encode

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: $HOME/work/encode.zip
