name: ATest

on: workflow_dispatch

jobs:
  build-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set PATH
      run: |
        echo 'export PATH="/usr/local/bin:${PATH}"' >> $HOME/.bashrc
      shell: bash

    - name: Downloading tools
      run: |
       pip install ffpb rclone
       sudo curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o /usr/local/bin/ffmpeg.tar.xz
       sudo tar -xvf /usr/local/bin/ffmpeg.tar.xz -C /usr/local/bin/
       sudo mv -v /usr/local/bin/ffmpeg-master-latest-linux64-gpl/bin/* /usr/local/bin
       chmod a+rx /usr/local/bin/ffmpeg

    - name: Download video
      run: |
        cd $HOME && pwd && mkdir encode
        cd $HOME && cd encode && curl "https://share.secretz.workers.dev/2:/SGCAM_20231022_020132577.ACTIVE.mp4" -o Video.mp4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential aom-tools nasm libtool python3-pip cython3 python3 clang autoconf ffmpeg libavformat-dev libavfilter-dev libavdevice-dev

    - name: Build Docker Image if not cached
      run: |
        cd Av1an
        docker build -t "av1an" .
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: |
          /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/*.Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Encode
      run: |
        cd $HOME && cd encode
        for input_video in $(find . -name "*.mp4"); do
          output_video="$HOME/encode/$(basename $input_video .mp4).mp4"
          docker run --privileged -v "/home/runner/encode":/videos --user $(id -u):$(id -g) -i --rm av1an -i "Video.mp4" --ffmpeg " -map 0 -c:s copy" --concat mkvmerge --verbose -e x265 -v " -D 10 -p veryslow --rc-lookahead 25 --rdoq-level 2 --bframes 8 --ref 4 --subme 3 --qcomp 0.75 --aq-mode 3 --aq-strength 1.00 --psy-rd 2.00 --psy-rdoq 1.00 --no-sao --crf 21 " -a="-c:a copy" -o "Output.mkv"
        done

    - name: Zip
      run: |
        cd $HOME

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Upload
        path: /home/runner/encode/Output.mkv
